services:
  db:
    image: postgres:15
    container_name: dbcrd05
    volumes:
      - ./dbcrd_05-data:/var/lib/postgresql/data/
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: CMD-SHELL pg_isready -U $${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  dbcrd_05_data:
