# Generated by Django 5.2.4 on 2025-07-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('ville', models.CharField(max_length=255, verbose_name='ville')),
                ('annee_creation', models.IntegerField(blank=True, null=True, verbose_name='annee_creation')),
                ('stade_nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='stade_nom')),
                ('stade_annee_creation', models.IntegerField(blank=True, null=True, verbose_name='stade_annee_creation')),
                ('stade_capacite', models.IntegerField(blank=True, default=0, null=True, verbose_name='stade_capacite')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('groupe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=8, verbose_name='groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('iso', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
            ],
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('surface_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='surface')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('poste_id', models.IntegerField(primary_key=True, serialize=False)),
                ('poste', models.CharField(max_length=4)),
                ('nom', models.CharField(max_length=100, verbose_name='poste')),
                ('groupe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('joueur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('prenom', models.CharField(blank=True, max_length=255, null=True, verbose_name='prenom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date_naissance')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.club')),
                ('iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.pays')),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.poste')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='surface_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.surface'),
        ),
    ]
